const normalizedLabel = {
  typeSemantique_1: 'Type sémantique',
  categorie_1: 'Catégorie',
  construction_1: 'Construction',
  typeConstruction_1: 'Type de construction',
  typeSemantique_2: 'Type sémantique',
  categorie_2: 'Catégorie',
  construction_2: 'Construction',
  typeConstruction_2: 'Type de construction',
  complexite: 'Complexité',
  orientation: 'Orientation',
  definitionConcrete: 'Définition concrète',
  definitionAbstraite: 'Définition abstraite',
  constructionPhonologique_1: 'Construction phonologique',
  rad: 'Radicale',
  constructionPhonologique_2: 'Construction phonologique',
  rad_2: 'Radicale',
  relationPhonologiqueAbstraite: 'Relation phonologique abstraite',
  seqCommRad1Rad_2: 'Séquence commune des radicaux',
  relationPhonologieConcrete: 'Relation phonologie concrète',
  st_1: 'St',
  st_2: 'St',
  categorie: 'Catégorie',
  construction: 'Construction',
  typeConstruction: 'Type de construction',
  typeSemantique: 'Type sémantique',
  graph: 'Graphie',
};

export default normalizedLabel;
